export const ROUTES = {
  STACK: {
    MAIN: "Main",
    AUTH: "Auth",
    REGISTER: "Register",
    HOMEPAGE: "Homepage",
    CATALOG: "Catalog",
    CHAT: "Chat",
    CHATS: "Chats",
    MED: "Med",
    TUBE: "Tube",
    CABINET: "Cabinet",
    PAYMENTS: "Payments",
    DOCTOR: "Doctor",
    DOCTOR_CABINET: "DoctorCabinet",
    DOCTOR_CABINET_EDIT: "DoctorCabinetEdit",
    DOCTOR_CHAT: "DoctorChat",
    DOCTOR_APPOINTMENTS: "DoctorAppointments",
    CHILDRENS: "Childrens",
    CHILDREN: "Children",
    CHILDREN_DOCTORS: "ChildrenDoctors",
    CHILDREN_INFORMATION_ABOUT_CLINIC: "ChildrenInformationAboutClinic",
    SPISOKSOVETOV: "SpisokSovetov",
    MEDICALCARD: "MedicalCard",
    DOCTOR_RECORD_DETAIL: "DoctorRecordDetail",
    USER_CATALOG_DOCTORS: "UserCatalogDoctors",
    USER_CATALOG_SERVICES: "UserCatalogServices",
    USER_CATALOG_RECOMMENDATIONS: "UserCatalogRecommendations",
    USER_CATALOG_FULL_RECOMENDATION: "UserCatalogFullRecomendation",
    USER_CONSULTATION_HISTORY: "UserConsultationHistory",
    USER_FULL_CONSULTATION: "UserFullConsultation",
    ISTORIABOLEZNEI: "IstoriaBoleznei",
    CHILDREN_HEALTH_STATUS: "ChildrenHealthStatus",
    USER_FAVOURITE_DRUGS: "UserFavouritesDrugs",
    USER_ANALYZE_HISTORY: "UserAnalyzeHistory",
    USER_ISTORIA_PRIEMOV: "UserPriemiHistory",

    USER_DRUG_DETAIL_SCREEN: "UserDrugDetailScreen",
    USER_SPISOK_SOVETOV: "UserSpisokSovetov",
    USER_OPROS: "UserOpros",
    USER_RECOMMENDATIONS: "UserRecomendations",

    USER_EDIT_PROFILE: "UserEditProfile",
    USER_EDIT_CHILDRESN: "USER_EDIT_CHILDRESN",
    USER_ABOUT_DOCTOR: "UserAboutDoctor",
    USER_REGISTRATION_AT_CLINIC: "UserRegistrationAtClinic",
    USER_REGISTRATION_SUMMARY: "UserRegistrationSummary"
  },
  TABS: {
    HOME: "HomeTab",
    PROFILE: "ProfileTab",
    SETTINGS: "SettingsTab",
  },
} as const;

export const TEXTS = {
  HEADER: {
    HOME: "Главная",
    PROFILE: "Профиль",
    SETTINGS: "Настройки",
    CHAT: "Чат",
    CATALOG: "Каталог",
  },
  BUTTONS: {
    GO_TO_PROFILE: "Перейти в профиль",
    GO_TO_SETTINGS: "Перейти к настройкам",
    EDIT_PROFILE: "Редактировать профиль",
    BACK: "Назад",
  },
  CONTENT: {
    HOME: "Добро пожаловать на главный экран!",
    PROFILE: "Экран профиля пользователя",
    SETTINGS: "Экран настроек приложения",
  },
} as const;
